# Generated by Django 3.1.5 on 2022-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0004_auto_20220414_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(default='1980-01-01', verbose_name='date of birth'),
        ),
    ]
