# Generated by Django 3.1.5 on 2022-04-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0006_alter_cursus_id_alter_student_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
